server:
  port: 8081

keycloak:
  url: "http://nginx/auth"
  realm: "lgm8"
  client_id: "lgm8-auth-service"
  client_secret: "WIORS6x7eQueQVKF0h5rJSz1tAo0NKIQ"
  admin_user: "admin"
  admin_password: "admin"