server:
  port: 8081

keycloak:
  url: "http://nginx/auth"
  realm: "lgm8"
  client_id: "lgm8-auth-service"
  client_secret: "PqAPBND8Rdste8kCjWExUEengit7JCC9"
  admin_user: "admin"
  admin_password: "admin"