server:
  port: 8081

keycloak:
  url: "http://nginx/auth"
  realm: "lgm8"
  client_id: "lgm8-auth-service"
  client_secret: "test"
  admin_user: "admin"
  admin_password: "admin"

secrets:
  user_ver_scrt_key: "/run/secrets/user_verification_secret_key"